name: Release to Maven Central

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: Release project
    runs-on: ubuntu-latest

    steps:

      - name: Check out sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B

      - name: Deploy to Sonatype OSSRH
        uses: qcastel/github-actions-maven-release@master
        with:
          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          maven-args: "-DskipTests -s settings.xml"
          release-branch-name: "release"
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        #run: ./mvnw -B clean deploy -s settings.xml
        #run: ./mvnw -B release:clean release:prepare release:perform -s settings.xml
